# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pushToDB import *
import gui as user_window


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, -20, 471, 161))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.employeeNumInput = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeNumInput.text() == "admin"
        self.employeeNumInput.setGeometry(QtCore.QRect(400, 40, 411, 41))
        self.employeeNumInput.setObjectName("employeeNumInput")
        self.employeePinInput = QtWidgets.QLineEdit(self.centralwidget)
        self.employeePinInput.setGeometry(QtCore.QRect(400, 110, 411, 41))
        self.employeePinInput.setObjectName("employeePinInput")
        self.btn_logIn = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logIn.setGeometry(QtCore.QRect(460, 180, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logIn.setFont(font)
        self.btn_logIn.setObjectName("btn_logIn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.result = None

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #self.btn_logIn.clicked.connect(self.login)

    def login(self, emp_number, pin_number):
        try:
            #emp_number = self.employeeNumInput.text()
            #pin_number = self.employeePinInput.text()
            result = check_user_log_in(emp_number, pin_number)

            if result == "None":
                print("Error signing in!!!")
                return "No results found!"
            elif result[0][0] == "admin" and result[0][1] == "admin":
                print("Success!")
                return result
            else:
                return result

        except:
            print("Error signing in.")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign In"))
        self.label.setText(_translate("MainWindow", "Employee Number:"))
        self.label_2.setText(_translate("MainWindow", "PIN Number:"))
        self.btn_logIn.setText(_translate("MainWindow", "LOG IN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
